[package]
name = "crates_deps_git"
version = "0.1.0"
authors = ["Rainer Stropek <rainer@software-architects.at>"]
edition = "2024"

[dependencies]
rand = "0.9"
num-format = "0.4"
mth_calc = { git = "https://github.com/rstropek/mth-calc" }
